### ISSUE TITLE
Address page tab rolls out of mobile view on selection

### ISSUE THREAD

**Issue by yvaskov** [blockscout/frontend#2268] opened 2024-09-25 11:09 UTC
## Description

When an address page tab is selected, it rolls out of view.

https://github.com/user-attachments/assets/fd806e26-bf72-4503-aff1-58abc0d4d9f2

## Version

[v1.34.1](https://github.com/blockscout/frontend/tree/v1.34.1)

**Comment by tom2drum** [comment] 2024-09-26 10:55
Duplicate of #2107. The fix is scheduled for the v1.35.0 release.

**Closed by tom2drum** 2024-09-26 10:55 UTC
Labels: bug
